# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a03a69e0f04b2a1a1b5234cd7ed918145ae0df46e1837cb3069101b392b5cfc4dadf848420bd806a25d8c56984062829ac5d470e37b2bf0528c8da2e9232e37

test:
  secret_key_base: 99cb6799753cb112b2c96966817eb0a94d7aebe946cee316b642dfada21f52c1a9d6c01c14ecae20d7735e9eb31119b01f08ad26d818b7896ecc4b5b939a248a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
